### ISSUE TITLE
Some question about how to calculate ppl

### ISSUE THREAD

**Issue by broalantaps** [getao/icae#17]
Could you describe more clearly how you get the PPL result in Table 6 and Figure 6(right)? Why memory slot lower than original text in Table 6 but higher than original text in Figure 6(right)? It would be highly appreciated if you could reply my issue. Thanks~

**Comment by broalantaps** [comment]
![image](https://github.com/getao/icae/assets/89376165/73c66e6f-9a28-4561-ae7c-3d31f1c4cf87)
![image](https://github.com/getao/icae/assets/89376165/fd746f09-32c9-41bd-8748-fd37b25c7259)

**Comment by getao** [comment]
Thank you for your question. In the Table, original context means the 512-token original context, memory slot means compressed memory slots (length=128). Using compressed memory slots yields the ppl=9.18 (Llama-2 7b), while using the original 512-token context yields better ppl=8.81, which is consistent in the Figure -- 128-token memory slots underperforms 512-token original context.

In the Figure, given the same context length (e.g., 512), 512 memory slots is actually from 4x original context length (2048). Therefore, 512 memory slots performs better than 512 original context length because the 512 memory slots actually represents 2048-token original context.

**Comment by broalantaps** [comment]
Thanks for your reply. Have you ever try to fix length(eg. 128) and add token(eg. 512 tokens or 128 memory slots), then calculate the ppl yield from last fix tokens(eg. 128). Just want to know whether can decrease the original text ppl when I insert a memory slot to original text. Thanks~

**Comment by broalantaps** [comment]
@getao ~

**Comment by getao** [comment]
According to our experiments, adding more memory slots can decrease the ppl if similar formats of data was seen in the pretraining phase.
