### ISSUE TITLE
About training ICAE from scratch

### ISSUE THREAD

**Issue by YoojuShin** [getao/icae#2]
Thanks for your work on ICAE, which makes it possible to compress prompt using a low-VRAM machine. 

I wonder if you can provide codes for training ICAE from scratch using PwC dataset.

I am trying to use the function `train_model` in `llama_icae_modeling.py`, but could not find how to preprocess PwC dataset.
https://github.com/getao/icae/blob/ac08ffbfa35430efd06b50518f1c9e60d57af97f/code/icae/llama_icae_learning.py#L18

Thanks!

**Comment by getao** [comment]
Thank you. The preprocess scripts will be uploaded soon.

**Comment by wanghao14** [comment]
@getao Thank you for sharing your projefct and it's incredibly intriguing! I've noticed that the current project description lacks to much details. Could you kindly offer a straightforward explanation, particularly on running the pre-training section? Additionally, I'd appreciate guidance on the necessary data processing steps. So that I can apply this project to my own data. Thanks!

**Comment by getao** [comment]
> @getao Thank you for sharing your projefct and it's incredibly intriguing! I've noticed that the current project description lacks to much details. Could you kindly offer a straightforward explanation, particularly on running the pre-training section? Additionally, I'd appreciate guidance on the necessary data processing steps. So that I can apply this project to my own data. Thanks!

Thank you for your interest. The data processing part is a little complicated because we run the experiments with very large-scale pretraining dataset. In our implementation, we use a streaming dataloader for efficiency. If your dataset is not large, you can use the default dataloader of the huggingface to train with it.

The preprocessing is not special. You can process the raw text using the following example scripts:
```
def pretrain_tokenize_function(examples, model, mem, lm_ratio=0.0):
    text_output = model.tokenizer(examples["text"], truncation=False, padding=False, return_attention_mask=False)
    text_output['prompt_answer_ids'] = []
    text_output['labels'] = []

    max_len = model.training_args.model_max_length  # heuristic

    for idx in range(len(text_output["input_ids"])):
        ae = True
        a, b = text_extraction(text_output["input_ids"][idx], max_len)
        if len(b) > 128 and random.random() <= lm_ratio:
            ae = False
            b = b[:max_len]

        text_output['input_ids'][idx] = a + mem

        # decoder part
        if ae:  # autoencoding objective
            prompt_ids = [model.ae_token_id]
            answer_ids = a + [model.eos_id]    # if ae, eos token
        else:   # lm objective
            prompt_ids = []
            answer_ids = b   # if lm, no eos token

        text_output['prompt_answer_ids'].append(prompt_ids + answer_ids)
        labels = [-100] * len(prompt_ids) + answer_ids
        text_output['labels'].append(labels)
    return text_output


def instruct_ft_tokenize_function(examples, model, mem):
    text_output = model.tokenizer(examples["input"], truncation=True, max_length=model.training_args.model_max_length, padding=False, return_attention_mask=False)
    prompt_output = model.tokenizer(examples['prompt'], add_special_tokens=False, padding=False)
    answer_output = model.tokenizer(examples['answer'], add_special_tokens=False, padding=False)

    text_output['prompt_answer_ids'] = []
    text_output['labels'] = []
    for idx in range(len(text_output["input_ids"])):
        # add mem tokens to the input
        text_output["input_ids"][idx] += mem

        # decoder part:
        prompt_ids = [model.ft_token_id] + prompt_output['input_ids'][idx] + [model.ft_token_id]
        answer_ids = answer_output['input_ids'][idx] + [model.eos_id]
        text_output['prompt_answer_ids'].append(prompt_ids + answer_ids)
        labels = [-100] * len(prompt_ids) + answer_ids
        text_output['labels'].append(labels)
    return text_output
```

We are working on organzing these codes together. A complete recipe will be released in the next update.

**Comment by getao** [comment]
Please refer to the v2 code for training
